'use client';
import { useEffect, useRef, useState } from 'react';
import Link from 'next/link';
import Image from 'next/image';
import { Box, ArrowUpRight, Upload, Layers3 } from 'lucide-react';
import { localIdentification, type IdentificationInput, type Candidate } from '../lib/providers';
import { validateImage } from '../lib/upload';

export function Intake({onOpen}:{onOpen:()=>void}) {
  const [name,setName]=useState('');const [manufacturer,setManufacturer]=useState('');const [model,setModel]=useState('');
  const [images,setImages]=useState<(IdentificationInput['images'][number]&{url:string})[]>([]);const urls=useRef<string[]>([]);
  const [error,setError]=useState('');const [busy,setBusy]=useState(false);const [candidate,setCandidate]=useState<Candidate|null>(null);const [stages,setStages]=useState<string[]>([]);
  useEffect(()=>()=>urls.current.forEach(url=>URL.revokeObjectURL(url)),[]);
  async function upload(files:FileList|null){if(!files)return;setBusy(true);setError('');setCandidate(null);try{if(files.length+images.length>6)throw new Error('Upload at most six images.');const metadata=await Promise.all(Array.from(files).map(async file=>({file,metadata:await validateImage(file)})));const next=metadata.map(({file,metadata})=>{const url=URL.createObjectURL(file);urls.current.push(url);return {...metadata,url};});setImages(current=>[...current,...next]);}catch(e){setError(e instanceof Error?e.message:'Image validation failed.');}finally{setBusy(false);}}
  async function identify(){setBusy(true);setError('');setCandidate(null);try{const result=await localIdentification.identifyProduct({name,manufacturer,model,images:images.map(({url,...rest})=>{void url;return rest;})});setStages(result.stages);setCandidate(result.candidates[0]);}catch(e){setError(e instanceof Error?e.message:'Identification failed.');}finally{setBusy(false);}}
  return <main className="landing"><header className="landing-header"><Link className="brand" href="/"><Box size={23}/><strong>inside<span> / </span></strong><span>Digital Twin Studio</span></Link><span className="badge">INTERACTIVE ENGINEERING LAB</span></header><div className="landing-grid"><section className="hero"><div className="eyebrow">SEE THE SYSTEM. UNDERSTAND THE PARTS.</div><h1>Understand Any Product<br/><em>From the Inside Out.</em></h1><p>Upload a product image, explore its digital twin, understand every component, simulate failures, and learn how to repair it.</p><button className="primary demo-button" onClick={onOpen}>Try Interactive Demo <ArrowUpRight size={20}/></button><div className="hero-proof"><span>15 selectable components</span><span>Deterministic simulation</span><span>No API key needed</span></div><div className="product-sketch" aria-hidden="true"><div className="sketch-layer back"/><div className="sketch-layer internals"><div className="sketch-board"/><div className="sketch-battery">Li-ion<br/>ENERGY MODULE</div></div><div className="sketch-layer front"><Layers3 size={32}/><span>DT–01</span></div><span className="sketch-label">PROCEDURAL MODEL / EDUCATIONAL DEMO</span></div></section>
  <section className="intake"><div className="eyebrow">01 / START AN EXPLORATION</div><h2>Bring a product into view.</h2><p className="muted">Start with an image or product name. We’ll show the available model and its confidence before opening it.</p><form onSubmit={e=>{e.preventDefault();void identify();}}><label className="upload"><Upload size={25}/><strong>{busy?'Validating…':'Choose product images'}</strong><span>JPEG, PNG, WebP · up to 8 MB each · 6 views</span><input type="file" accept="image/jpeg,image/png,image/webp" multiple disabled={busy} onChange={e=>{void upload(e.target.files);e.target.value='';}} aria-label="Product images"/></label>{images.length>0&&<div className="image-previews">{images.map((img,i)=><div key={img.url}><Image unoptimized width={90} height={70} src={img.url} alt={`Product view ${i+1}`}/><select aria-label={`Image ${i+1} view`} value={img.view} onChange={e=>setImages(all=>all.map((v,n)=>n===i?{...v,view:e.target.value as typeof v.view}:v))}>{['front','back','left','right','top','bottom','detail'].map(v=><option key={v}>{v}</option>)}</select><button type="button" aria-label={`Remove image ${i+1}`} onClick={()=>{URL.revokeObjectURL(img.url);setImages(all=>all.filter((_,n)=>n!==i));}}>Remove</button></div>)}</div>}
  <label className="field">Product name<input value={name} onChange={e=>{setName(e.target.value);setCandidate(null);}} placeholder="e.g. Smartphone" maxLength={150}/></label><div className="form-pair"><label className="field">Manufacturer <span>optional</span><input value={manufacturer} onChange={e=>{setManufacturer(e.target.value);setCandidate(null);}} placeholder="Manufacturer" maxLength={100}/></label><label className="field">Model <span>optional</span><input value={model} onChange={e=>{setModel(e.target.value);setCandidate(null);}} placeholder="Model number" maxLength={100}/></label></div><button className="primary wide" type="submit" disabled={busy||(!name.trim()&&!images.length)}>Analyze Product <ArrowUpRight size={18}/></button></form><p className="caption">Images stay in this browser. The local fallback matches text metadata; it does not perform image recognition.</p>{error&&<p role="alert" className="warning">{error}</p>}{candidate&&<div className="candidate" role="status"><span className="badge">{Math.round(candidate.confidence*100)}% CATEGORY CONFIDENCE</span><h3>{candidate.name}</h3><p>{candidate.reason}</p><ul>{stages.map(stage=><li key={stage}>{stage}</li>)}</ul><button className="primary wide" onClick={onOpen}>Use educational demo model →</button></div>}</section></div><footer className="landing-footer">EXPLORE / SIMULATE / UNDERSTAND <span>Demo data is illustrative, not manufacturer-verified.</span></footer></main>;
}

